// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdEG8eJfF-Lw5zBcIGaMxZjFT-jkgAGY',
    appId: '1:1078746643895:web:eb0d4252b74547d5cbfc32',
    messagingSenderId: '1078746643895',
    projectId: 'meranti-hub',
    authDomain: 'meranti-hub.firebaseapp.com',
    storageBucket: 'meranti-hub.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC6A8Ou-bwBt_4N1zOjrXisJqpHB41tQc',
    appId: '1:1078746643895:android:8f41374a93cdcffacbfc32',
    messagingSenderId: '1078746643895',
    projectId: 'meranti-hub',
    storageBucket: 'meranti-hub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUObk702Gl-ufn3zpIZHJvAIsyUQok7aU',
    appId: '1:1078746643895:ios:2e63149e426e8879cbfc32',
    messagingSenderId: '1078746643895',
    projectId: 'meranti-hub',
    storageBucket: 'meranti-hub.appspot.com',
    iosClientId: '1078746643895-r00nk80lnumkubhl9l3l84v4nao38og6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sprint1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUObk702Gl-ufn3zpIZHJvAIsyUQok7aU',
    appId: '1:1078746643895:ios:2e63149e426e8879cbfc32',
    messagingSenderId: '1078746643895',
    projectId: 'meranti-hub',
    storageBucket: 'meranti-hub.appspot.com',
    iosClientId: '1078746643895-r00nk80lnumkubhl9l3l84v4nao38og6.apps.googleusercontent.com',
    iosBundleId: 'com.example.sprint1',
  );
}
